Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 0's token_index 119
Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 1's token_index 213
Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 2's token_index 38
Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 3's token_index 285
Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 4's token_index 346
Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 5's token_index 94
Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 6's token_index 111
Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 7's token_index 305
Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 8's token_index 419
Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 9's token_index 118
Sat 27 May 2017 15:55:58 API.py [line:547] INFO 200 statuses/filter text thread 10's token_index 344
Sat 27 May 2017 15:56:01 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:01 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:02 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:02 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:03 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:03 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:04 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:04 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:05 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:05 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:08 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:08 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:09 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:09 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:11 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:11 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:12 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:12 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:13 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:13 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:14 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:14 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:15 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:15 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:16 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:16 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:18 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:18 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:20 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:20 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:21 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:21 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:23 TwitterError.py [line:21] WARNING <class 'requests.exceptions.SSLError'> ('_ssl.c:645: The handshake operation timed out',)
Sat 27 May 2017 15:56:23 API.py [line:208] WARNING ('_ssl.c:645: The handshake operation timed out',)
Sat 27 May 2017 15:56:23 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:23 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:25 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:25 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:26 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:26 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:28 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:28 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:29 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:29 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:30 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:30 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:31 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:31 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:33 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:33 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:36 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:36 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:38 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:38 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', error(10054, '')))
Sat 27 May 2017 15:56:40 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'305433319', u'user_id': 305433319, u'id': 852294773192802304L, u'id_str': u'852294773192802304'}, u'timestamp_ms': u'1495871797118'}}
Sat 27 May 2017 15:56:48 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:48 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:58 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:56:59 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:57:09 TwitterError.py [line:21] WARNING <class 'requests.exceptions.SSLError'> ('_ssl.c:645: The handshake operation timed out',)
Sat 27 May 2017 15:57:09 API.py [line:208] WARNING ('_ssl.c:645: The handshake operation timed out',)
Sat 27 May 2017 15:57:18 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'330895534', u'user_id': 330895534, u'id': 868193282018377728L, u'id_str': u'868193282018377728'}, u'timestamp_ms': u'1495871810925'}}
Sat 27 May 2017 15:57:19 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:57:19 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:57:19 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'305433319', u'user_id': 305433319, u'id': 851501656751587330L, u'id_str': u'851501656751587330'}, u'timestamp_ms': u'1495871816418'}}
Sat 27 May 2017 15:57:29 TwitterError.py [line:21] WARNING <class 'requests.exceptions.ConnectionError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:57:29 API.py [line:208] WARNING HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',)))
Sat 27 May 2017 15:57:34 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'2192072359', u'user_id': 2192072359L, u'id': 868375210713632768L, u'id_str': u'868375210713632768'}, u'timestamp_ms': u'1495871828207'}}
Sat 27 May 2017 15:57:50 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'330895534', u'user_id': 330895534, u'id': 868131217920729088L, u'id_str': u'868131217920729088'}, u'timestamp_ms': u'1495871839784'}}
Sat 27 May 2017 15:57:52 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'4240100074', u'user_id': 4240100074L, u'id': 798016710389469185L, u'id_str': u'798016710389469185'}, u'timestamp_ms': u'1495871846048'}}
Sat 27 May 2017 15:57:52 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'19989765', u'user_id': 19989765, u'id': 868227470507491328L, u'id_str': u'868227470507491328'}, u'timestamp_ms': u'1495871848438'}}
Sat 27 May 2017 15:57:56 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'21295515', u'user_id': 21295515, u'id': 867516792213835776L, u'id_str': u'867516792213835776'}, u'timestamp_ms': u'1495871864185'}}
Sat 27 May 2017 15:58:06 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'69504390', u'user_id': 69504390, u'id': 868375552977195009L, u'id_str': u'868375552977195009'}, u'timestamp_ms': u'1495871855505'}}
Sat 27 May 2017 15:58:33 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'305433319', u'user_id': 305433319, u'id': 850157526129623041L, u'id_str': u'850157526129623041'}, u'timestamp_ms': u'1495871888101'}}
Sat 27 May 2017 15:58:36 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'569581021', u'user_id': 569581021, u'id': 868217327778643968L, u'id_str': u'868217327778643968'}, u'timestamp_ms': u'1495871827711'}}
Sat 27 May 2017 15:58:46 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'1060010336', u'user_id': 1060010336, u'id': 868375061807411201L, u'id_str': u'868375061807411201'}, u'timestamp_ms': u'1495871894415'}}
Sat 27 May 2017 15:58:53 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'2317074942', u'user_id': 2317074942L, u'id': 868375711970676736L, u'id_str': u'868375711970676736'}, u'timestamp_ms': u'1495871885584'}}
Sat 27 May 2017 15:58:58 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'305433319', u'user_id': 305433319, u'id': 850142844689850368L, u'id_str': u'850142844689850368'}, u'timestamp_ms': u'1495871915376'}}
Sat 27 May 2017 15:58:59 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'21216420', u'user_id': 21216420, u'id': 754604259468017664L, u'id_str': u'754604259468017664'}, u'timestamp_ms': u'1495871887087'}}
Sat 27 May 2017 15:59:08 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'365681790', u'user_id': 365681790, u'id': 866939575721226240L, u'id_str': u'866939575721226240'}, u'timestamp_ms': u'1495871922275'}}
Sat 27 May 2017 15:59:25 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'203034083', u'user_id': 203034083, u'id': 754608840839204864L, u'id_str': u'754608840839204864'}, u'timestamp_ms': u'1495871887097'}}
Sat 27 May 2017 15:59:28 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'140519723', u'user_id': 140519723, u'id': 868375941063614465L, u'id_str': u'868375941063614465'}, u'timestamp_ms': u'1495871952243'}}
Sat 27 May 2017 15:59:39 TwitterError.py [line:21] WARNING <class 'requests.packages.urllib3.exceptions.ReadTimeoutError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out.
Sat 27 May 2017 15:59:43 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'2804615370', u'user_id': 2804615370L, u'id': 868368466809503744L, u'id_str': u'868368466809503744'}, u'timestamp_ms': u'1495871942901'}}
Sat 27 May 2017 16:00:07 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'305433319', u'user_id': 305433319, u'id': 850079098021986304L, u'id_str': u'850079098021986304'}, u'timestamp_ms': u'1495871973765'}}
Sat 27 May 2017 16:00:13 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'426255265', u'user_id': 426255265, u'id': 868360892454363136L, u'id_str': u'868360892454363136'}, u'timestamp_ms': u'1495871956986'}}
Sat 27 May 2017 16:00:16 TwitterError.py [line:21] WARNING <class 'requests.packages.urllib3.exceptions.ReadTimeoutError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out.
Sat 27 May 2017 16:00:16 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'242460409', u'user_id': 242460409, u'id': 868192609151459333L, u'id_str': u'868192609151459333'}, u'timestamp_ms': u'1495871940212'}}
Sat 27 May 2017 16:00:28 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'305433319', u'user_id': 305433319, u'id': 850077496900894720L, u'id_str': u'850077496900894720'}, u'timestamp_ms': u'1495871986720'}}
Sat 27 May 2017 16:00:34 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'555370896', u'user_id': 555370896, u'id': 868179133876105217L, u'id_str': u'868179133876105217'}, u'timestamp_ms': u'1495871980096'}}
Sat 27 May 2017 16:01:14 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'2391164419', u'user_id': 2391164419L, u'id': 867761052162838528L, u'id_str': u'867761052162838528'}, u'timestamp_ms': u'1495872037327'}}
Sat 27 May 2017 16:01:22 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'1060010336', u'user_id': 1060010336, u'id': 868376441024643072L, u'id_str': u'868376441024643072'}, u'timestamp_ms': u'1495872072434'}}
Sat 27 May 2017 16:01:33 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'1335002192', u'user_id': 1335002192, u'id': 862287514735972353L, u'id_str': u'862287514735972353'}, u'timestamp_ms': u'1495872085524'}}
Sat 27 May 2017 16:01:36 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'305433319', u'user_id': 305433319, u'id': 849396288537886720L, u'id_str': u'849396288537886720'}, u'timestamp_ms': u'1495872027977'}}
Sat 27 May 2017 16:01:40 TwitterError.py [line:21] WARNING <class 'requests.packages.urllib3.exceptions.ReadTimeoutError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out.
Sat 27 May 2017 16:01:42 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'305433319', u'user_id': 305433319, u'id': 849399713145204738L, u'id_str': u'849399713145204738'}, u'timestamp_ms': u'1495872035573'}}
Sat 27 May 2017 16:01:45 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'3297217592', u'user_id': 3297217592L, u'id': 868374995722018818L, u'id_str': u'868374995722018818'}, u'timestamp_ms': u'1495872066316'}}
Sat 27 May 2017 16:02:00 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'2192072359', u'user_id': 2192072359L, u'id': 868376054070693888L, u'id_str': u'868376054070693888'}, u'timestamp_ms': u'1495872049816'}}
Sat 27 May 2017 16:02:21 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'136986438', u'user_id': 136986438, u'id': 868370419094630401L, u'id_str': u'868370419094630401'}, u'timestamp_ms': u'1495872085905'}}
Sat 27 May 2017 16:02:46 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'17839060', u'user_id': 17839060, u'id': 868376581584150528L, u'id_str': u'868376581584150528'}, u'timestamp_ms': u'1495872090557'}}
Sat 27 May 2017 16:02:52 TwitterError.py [line:21] WARNING <class 'requests.packages.urllib3.exceptions.ReadTimeoutError'> HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out.
Sat 27 May 2017 16:02:52 API.py [line:223] ERROR 400 statuses/filter text {u'delete': {u'status': {u'user_id_str': u'305433319', u'user_id': 305433319, u'id': 848667827145854976L, u'id_str': u'848667827145854976'}, u'timestamp_ms': u'1495872075685'}}
